<a href="https://colab.research.google.com/github/rhehgus02/ESAA/blob/main/%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_%EA%B0%80%EC%9D%B4%EB%93%9C(p_1~38).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **<01> 머신러닝의 개념**

 

*  머신러닝: 애플리케이션을 수정하지 않고도 데이터를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘 기법 ex) 금융 사기 거래를 적발하는 프로그램

*   머신러닝의 특징:
    * 데이터를 기반으로 숨겨진 패턴을 스스로 인지하고 신뢰도 있는 예측 결과를 도출해 냄
    * 데이터를 기반으로 통계적인 신뢰도를 강화하고 예측 오류를 최소화하기 위한 다양한 수학적 기법을 적용시킴


---

#### **1. 머신러닝의 분류**

1) 지도학습

* 분류
* 회귀
* 추천시스템
* 시각/음성 감지/인지
* 텍스트 분석, NLP

2) 비지도학습
* 클러스터링
* 차원 축소
* 강화학습


---



#### **2. 데이터 전쟁**

* 데이터 vs 머신러닝 알고리즘

    -> 머신러닝의 데이터에 매우 의존적이기 때문에 좋은 품질의 데이터를 갖추지 못한다면 머신러닝의 수행 결과도 좋을 수 없음

    -> 그러므로 최적의 머신러닝 알고리즘과 모델 파라미터를 구축하는 능력도 중요하지만 데이터를 이해하고 효율적으로 가공, 처리, 추출해 최적의 데이터를 갖추는 것이 더 중요함

---

#### **3. 파이썬과 R 기반의 머신러닝 비교**

* 머신러닝 프로그램을 작성할 수 있는 대표적인 오픈 소스 프로그램: 파이썬, R

* R
    * 통계 전용 프로그램 언어
    * 다양한 많은 통계 패키지를 보유
     
     -> 개발 언어에 익숙하지 않으나 통계 분석에 능한 현업 사용자에게 추천

* 파이썬
    * 다양한 영역에서 사용되는 개발 전문 프로그램 언어
    * 직관적인 문법과 객체지향과 함수형 프로그래밍을 모두 포괄
    * 파이썬에 대한 관심이 급격히 증가했으며 프로그래밍 세계를 점령하고 있음
     
     -> 이제 머신러닝을 시작하거나 개발자라면 R보다는 파이썬 추천

---

# **<02> 파이썬 머신러닝 생태계를 구성하는 주요 패키지**

* 머신러닝 패키지: 사이킷런(데이터 마이닝 기반)

* 딥러닝 패키지: 텐서플로, 케라스

* 행렬/선행대수/통계 패키지: 넘파이(행렬과 선행대수), 사이파이(통계 패키지)

* 데이터 핸들링: 판다스(2차원 데이터 처리)

* 시각화: 맷플롯립, 시본(맷플롯립을 보완)


---

# **<03> 넘파이**

*  넘파이: 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지

* C/C++과 같은 저수준 언어 기반의 호환 API 제공

* 빠른 배열 연산 속도 보장

* 다양한 데이터 핸들링 기능을 제공하지만 판다스의 편리성에는 미치지 못함

* 머신러닝 알고리즘이 넘파이 기반으로 작성돼 있으므로 넘파이를 이해하는 것은 파이썬 기반의 머신러닝에서 매우 중요

---

#### **1. 넘파이 ndarray 개요**

1) 넘파이 모듈 임포트:  `import numpy as np`

2) 넘파이 기반 데이터 타입: ndarray

3) `np.array()` 함수: 다양한 인자를 입력 받아서 ndarray로 변환

4) `ndarray.shape`: ndarray의 차원과 크기를 튜플 형태로 나타냄

5) `ndarray.ndim`: 각 ndarray의 차원을 나타냄

In [22]:
import numpy as np

In [23]:
array1 = np.array([1, 2, 3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1, 2, 3],
                  [2, 3, 4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1, 2, 3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)




>> `shape (3, )`: 1차원, 3개의 데이터 

>> `shape (2, 3)`: 2차원, 2행 3열, 6개의 데이터



In [24]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim,
                                                                array2.ndim,array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원




>> 리스트 [     ]: 1차원

>> 리스트 [[      ]] : 2차원



---
#### **2. ndarray의 데이터 타입**

* ndarray내 데이터값: 숫자, 문자열, 불 모두 가능

    * 리스트와 다르게 같은 데이터 타입끼리만 가능
 
   -> 다른 데이터 유형이 함께 있는 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 타입으로 형 변환 

1) `dtype`: ndarray의 데이터 타입 확인

2) `astype()`: ndarray내 데이터 타입을 변경

In [25]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [26]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3=[1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


>> int형 + 문자열  ->  모두 유니코드 문자열

>> int형 + float형 -> 모두 float64형  

In [27]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64') 
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32') 
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1]) 
array_int2 = array_float1.astype('int32') 
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


>> float를 int형으로 변경할 때는 소수점 이하 절삭

---

#### **3. ndarray를 편리하게 생성하기 - arange, zeros, ones**

1) `arange(n)`: 0부터 (n-1)까지의 값을 순차적으로 ndarray의 데이터 값으로 변환

2) `zeros()`: 함수 인자로 튜플 형태의 shape 값을 입력하면 해당 shape를 모두 0으로 채운 ndarray 반환

3) `ones()`: `zeros()`와 같지만 값을 모두 1로 채움 

In [28]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


>> 0부터 (stop-1)인 9까지의 연속 숫가 값으로 구성된 1차원 ndarray 생성

>> `range()`와 유사하게 start 값도 부여할 수 있음

In [29]:
zero_array = np.zeros((3, 2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


>> 함수 인자로 dtype을 정해주지 않았을 때 default 데이터 타입: float64형

---
#### **4. ndarray의 차원과 크기를 변경하는 reshape()**

1) `reshape()`: ndarray를 특정 차원 및 크기로 변환

* !! -1 인자를 사용하면 다른 고정값에 맞게 ndarray를 변환시킴 !!

2) `reshape(-1, 1)`: 2차원이며 1개의 열을 가진 ndarray로 변환됨

3) `tolist()`: ndarray를 리스트 자료형으로 변환

In [30]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [31]:
array1.reshape(4,3)

ValueError: ignored

>> 지정된 사이즈로 변경이 불가능하면 오류 발생

In [32]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1, 5)
print('array2 shape:', array2.shape)

array3 = array1.reshape(5, -1)
print('array3 shape', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape (5, 2)


>> `array1.reshape(-1, 5)`에서 고정값이 5이므로 열의 수를 5로 고정하고, 이에 맞게 행의 수를 2로 변환시킴

>> `array2.reshape(5, -1)`에서 고정값이 5이므로 행의 수를 5로 고정하고, 이에 맞게 열의 수를 2로 변환시킴

In [33]:
array1 = np.arange(10)
array4 = array1.reshape(-1, 4)

ValueError: ignored

>> 열의 고정값이 4일 때는 크기가 10인 ndarray를 만들 수 없으므로 오류 발생

In [34]:
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2)) 
print('array3d: \n', array3d.tolist())
print()

# 3차원 ndarray를 2차원으로 변환
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist()) 
print('array5 shape:', array5.shape)
print()

# 1차원 ndarray를 2차원으로 변환
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist()) 
print('array6 shape:', array6.shape)

array3d: 
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]

array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)

array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


>> `reshape(-1, 1)`을 이용해 3차원을 2차원으로, 1차원을 2차원으로 변경

---

#### **5. 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)**

1) 특정한 데이터만 추출: 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터 반환
* [  ]안에 인덱스 값 입력

2) 슬라이싱: 연속된 인덱스상의 데이터 추출
* [a:b] : a 인덱스부터 (b-1) 인덱스까지 데이터 반환

3) 팬시 인덱싱: 일정한 인덱스 집합을 리스트 또는 ndarray 형태로 지정하면 해당 위치에 있는 데이터 반환

4) 불린 인덱싱: 특정 조건에 따른 True/False 값 집합을 기준으로 True에 해당하는 인덱스 위치에 있는 데이터 반환

---

#### **5-1. 단일 값 추출**

* axis0: 행 방향의 축

* axis1: 열 방향의 축

In [35]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2] 
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


>> 인덱스는 0부터 시작하므로 `array1[2]`는 3번째 인덱스 위치의 데이터 값 반환



In [36]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


>> 마이너스 기호 이용 시 뒤에서부터 데이터 추출

>> 인덱스 [-1]은 뒤에서 첫 번째 데이터

In [37]:
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


>> 단일 인덱스를 이용해 ndarray내의 데이터 값을 간단히 수정 가능

In [38]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0, 0])
print('(row=0, col=1) index 가리키는 값:', array2d[0, 1])
print('(row=1, col=0) index 가리키는 값:', array2d[1, 0])
print('(row=2, col=2) index 가리키는 값:', array2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


>> 다차원 ndarray에서 단일 값 추출

>> `array[0, 1]`: 첫 번째 행, 두 번째 열의 값 추출

>> (row=0, col=1)은 사실 [axis0=0, axis1=1]

---

#### **5-2. 슬라이싱**

In [39]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [40]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5=array1[3:]
print(array5)

array6=array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


>> ':' 기호 앞 시작 인덱스 생략하면 자동으로 맨 처음 인덱스인 0으로 간주

>> ':' 기호 뒤 종료 인덱스를 생략하면 자동으로 맨 마지막 인덱스로 간주

In [41]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2]\n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3]\n', array2d[1:3, 0:3])
print('array2d[1:3, :]\n', array2d[1:3, :])
print('array2d[:, :]\n', array2d[:, :])
print('array2d[:2, 1:]\n', array2d[:2, 1:])
print('array2d[:2, 0]\n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]]
array2d[:2, 0]
 [1 4]


>> 행, 열 각각의 인덱스에 슬라이싱 적용

>> `array2d[:2, 0]`과 같이 한 쪽에는 슬라이싱, 한 쪽에는 단일 값 인덱스를 적용해도 됨

In [42]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


>> `array2d[0]`: 첫 번째 행 ndarray 반환

>> 2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray를 반환

>> 3차원 ndarray에서 뒤에 오는 인덱스를 없애면 2차원 ndarray를 반환

---

#### **5-3. 팬시 인덱싱**

In [43]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] =>',array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] =>',array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] =>', array5.tolist())

array2d[[0,1], 2] => [3, 6]
array2d[[0,1], 0:2] => [[1, 2], [4, 5]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


>> `array2d[[0,1], 2]` -> 1, 2행 + 3열

>> `array2d[[0,1], 0:2]` -> 1, 2행 + 1, 2열

>> `array2d[[0,1]]` -> 1, 2행 + 모든 열

---
#### **5-4. 불린 인덱싱**

In [44]:
array1d = np.arange(start=1, stop=10)
# [] 안에 array1d>5 Boolean indexing을 적용
array3 = array1d[array1d>5]
print('array1d>5 불린 인덱싱 결과 값:',array3)

array1d>5 불린 인덱싱 결과 값: [6 7 8 9]


In [45]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

>> False, True로 이루어진 ndarray 객체 반환

>> 조건에 만족하는 데이터가 있는 위치는 True 값이, 그렇지 않으면 False 값이 반환

In [46]:
boolean_indexes = np.array([False,False,False,False,False,True,True,True,True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:', array3)

불린 인덱스로 필터링 결과: [6 7 8 9]


>> True 값에 해당하는 위치의 데이터만 반환

In [47]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과:',array4)

일반 인덱스로 필터링 결과: [6 7 8 9]


---
#### **6. 행렬의 정렬 - sort()와 argsort()**

1) `np.sort(인자)`: 원 행렬은 그대로 유지, 원 행렬의 정렬된 행렬 반환

2) `인자.sort()`: 원 행렬 자체를 정렬 형태로 변환, 반환 값은 None

3) `np.argsort(인자)`: 정렬된 행렬에서 차례로로 원본 행렬 인덱스를 반환 

---

#### **6-1. 행렬 정렬**

In [48]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)
# np.sort()로 정렬렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)
# ndarray.sort()로 정렬렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


>> 기본적으로 오름차순으로 행렬 내 원소 정렬

In [49]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc) 

내림차순으로 정렬: [9 5 3 1]


>> 내림차순 정렬: `np.sort()[::-1]`

In [50]:
array2d = np.array([[8,12],
                   [7,1]])
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


>> `axis=0`: 행 방향 축, 열 방향으로 정렬

>> `axis=1`: 열 방향 축, 행 방향으로 정렬렬

#### **6-2. 정렬된 행렬의 인덱스를 반환하기**



In [51]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices) 

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [52]:
org_array = np.array([3,1,9,5])
sort_indices_desc=np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc) 

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [53]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순 정렬시 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순 정렬시 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


>> `np.argsort()`를 이용해 반환된 인덱스를 다른 ndarray에 팬시 인덱스로 적용시킬 수 있음

---
#### **7. 선행대수 연산 - 행렬 내적과 전치 행렬 구하기**

 1) `np.dot(A, B)`: A와 B의 행렬 내적(행렬 곱)

 2) `tranpose()`: 전치 행렬

In [54]:
A = np.array([[1,2,3],
             [4,5,6]])
B = np.array([[7,8],
             [9,10],
             [11,12]])

dot_product = np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [55]:
A = np.array([[1,2],
             [3,4]])

transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
